SELECT * FROM assignment.worker;
USE ASSIGNMENT ;
SELECT * FROM WORKER ;
SELECT * FROM WORKER ORDER BY FIRST_NAME ASC ;
SELECT * FROM WORKER ORDER BY DEPARTMENT DESC ;
SELECT * FROM WORKER WHERE FIRST_NAME IN ('VIPUL','SATISH') ;
SELECT * FROM WORKER WHERE FIRST_NAME LIKE '_____%H' ;
SELECT * FROM WORKER WHERE SALARY = 100000 ;
SELECT DISTINCT SALARY FROM WORKER ;
SELECT DISTINCT JOINING_DATE FROM WORKER ;
SELECT DISTINCT DEPARTMENT FROM WORKER ; 
SELECT * FROM WORKER LIMIT 6 ;
SELECT COUNT(WORKER_ID),DEPARTMENT FROM WORKER GROUP BY DEPARTMENT ;
SELECT COUNT(WORKER_ID),DEPARTMENT FROM WORKER GROUP BY DEPARTMENT HAVING COUNT(WORKER_ID) < 5 ;
	